### ISSUE TITLE
Add check for dead actor

### ISSUE THREAD

**Issue by ShoukangHong** [Echizen-ham/SRPGcore#3]
In `Game_System.prototype.setSrpgActors`
change `var array = $gameParty.allMembers()` to `var array = $gameParty.allMembers().filter(function(actor){return actor.isAlive()})`
So that dead actors won't show up in the battle.

**Comment by Echizen-ham** [comment]
Thank you for the issues.
First of all, regarding this function, I think that whether it is necessary or not depends on the game produced by each person, so I will put it in a form that can be changed with the plug-in parameter.
For example, I'm currently creating a skill to revive a dead actor, so I don't want to remove the dead actor from the List from the beginning.

**Comment by ShoukangHong** [comment]
Sure, that's a good solution, and I'm looking forward to the revive skill!
